### ISSUE TITLE
Unable to upload .mp4 file

### ISSUE THREAD

**Issue by FabioRosado** [anaconda/pyscript-dot-com-issues#1]
This issue was brought to his repository from https://github.com/pyscript/pyscript/issues/1978

> ### Checklist
> 
> - [X] I added a descriptive title
> - [X] I searched for other issues and couldn't find a solution or duplication
> - [X] I already searched in Google and didn't find any good information or help
> 
> ### What happened?
> 
> @FabioRosado I am trying to upload .mp4 video file but upload shows blank after selection.
> 
> ### What browsers are you seeing the problem on? (if applicable)
> 
> Microsoft Edge
> 
> ### Console info
> 
> _No response_
> 
> ### Additional Context
> 
> _No response_

**Comment by FabioRosado** [comment]
Hello @nasrin1748 i think the issue of both this and #2 may be related, could you please tell us the size of each file that you are trying to upload?

We have a limit in the backend on how big a file can be uploaded, if you are having issues it's likely we need to improve errors from the backend

**Comment by FabioRosado** [comment]
Hello again! Just diagnosed this issue and confirmed that is likely your files were too big, currently we are allowed a max of 1MB files to be uploaded.

I have a fix for showing the error message and will be deployed this week

**Comment by ghost** [comment]
Yes. I am able to upload <1MB .mp4 and PDF.

**Comment by FabioRosado** [comment]
We will deploy to production today a fix so you get an alert when trying to upload any file that's over the limit

**Comment by FabioRosado** [comment]
Hello again, we deployed yesterday and we now show an alert when trying to upload any file that is larger than the allowed. 

I'll close this issue now, but please feel free to re-open or comment here if necessary
