### ISSUE TITLE
Filename and Foldername issue.

### ISSUE THREAD

**Issue by ghost** [anaconda/pyscript-dot-com-issues#4]
Folder can have same name as file but Py-script IDE throws an error when file name is given same as folder name.
File within folder same name is accepted but not outside of the folder.
<img width="223" alt="45" src="https://github.com/anaconda/pyscript-dot-com-issues/assets/79505893/c225e51f-5e8f-4929-bf20-364915a0ca07">

**Comment by alex-martinez** [comment]
Hi @nasrin1748, that is intentional. Files and folders cannot share the same name if they're at the same level as this is a naming conflict.
