### ISSUE TITLE
Display File on Drop doesn't work.

### ISSUE THREAD

**Issue by ghost** [anaconda/pyscript-dot-com-issues#5]
Dropping a file in the code area and was suppose to display the file.

**Comment by alex-martinez** [comment]
@nasrin1748 can you provide more context?

**Comment by ghost** [comment]
Was expecting pyscript.com to do the following. 
 https://www.youtube.com/watch?v=nDQ5oMnPTfM

**Comment by alex-martinez** [comment]
@nasrin1748 the video is private

**Comment by ghost** [comment]
> @nasrin1748 the video is private

It's public now.

**Comment by alex-martinez** [comment]
Ah I see. This isn't a bug, but more of a feature request. I'll create a ticket to add this feature 👍
